
-- Ricky
CREATE USER ricky SUPERUSER;
CREATE DATABASE ricky;
GRANT ALL PRIVILEGES ON DATABASE ricky TO ricky;

-- Rogerz
CREATE USER rogerz SUPERUSER;
CREATE DATABASE rogerz;
GRANT ALL PRIVILEGES ON DATABASE rogerz TO rogerz;

-- n
CREATE USER n SUPERUSER;
CREATE DATABASE n;
GRANT ALL PRIVILEGES ON DATABASE n TO n;

-- sophie
CREATE USER sophie SUPERUSER;
CREATE DATABASE sophie;
GRANT ALL PRIVILEGES ON DATABASE sophie TO sophie;

-- edward
CREATE USER edward SUPERUSER;
CREATE DATABASE edward;
GRANT ALL PRIVILEGES ON DATABASE edward TO edward;

-- frederic
CREATE USER frederic SUPERUSER;
CREATE DATABASE frederic;
GRANT ALL PRIVILEGES ON DATABASE frederic TO frederic;

-- alberto
CREATE USER alberto SUPERUSER;
CREATE DATABASE alberto;
GRANT ALL PRIVILEGES ON DATABASE alberto TO alberto;

-- stacko
CREATE USER stacko SUPERUSER;
CREATE DATABASE stacko;
GRANT ALL PRIVILEGES ON DATABASE stacko TO stacko;
